name: Deno CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  task-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.x
          cache: true

      - name: Run deno task fmt-ci
        run: deno task fmt-ci

      - name: Run deno task lint
        run: deno task lint

      - name: Run deno task test
        run: deno task test

      - name: Run deno task build
        run: deno task build

      - name: Verify no diff
        run: |
          git diff --exit-code
