name: Deno CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  task-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.x
          cache: true

      - name: Run deno task build
        run: deno task build

      - name: Run deno task fmt-ci
        run: deno task fmt-ci

      - name: Run deno task lint
        run: deno task lint

      - name: Run tests with coverage
        run: deno task test:cov

      - name: Generate coverage report
        run: deno task coverage

      - name: Check coverage threshold (80%)
        run: |
          COVERAGE_OUTPUT=$(deno task coverage)
          echo "$COVERAGE_OUTPUT"
          COVERAGE=$(echo "$COVERAGE_OUTPUT" | grep "All files" | sed 's/|//g' | awk '{print $NF}')
          echo "Extracted Coverage: ${COVERAGE}%"
          deno eval "
            const coverage = parseFloat('${COVERAGE}');
            if (isNaN(coverage)) {
              console.error('ERROR: Could not parse coverage value');
              Deno.exit(1);
            }
            if (coverage < 80) {
              console.error(\`ERROR: Coverage \${coverage}% is below the required 80% threshold\`);
              Deno.exit(1);
            } else {
              console.log(\`SUCCESS: Coverage \${coverage}% meets the 80% threshold\`);
            }
          "
