name: Deno CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  task-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.x
          cache: true

      - name: Run all tasks
        run: deno task all

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || (git commit -m "[skip ci] update build artifacts" && git push)
