name: Deno CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  task-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.x
          cache: true

      - name: Run deno fmt
        run: deno task fmt

      - name: Run commit fmt diff if needed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || (git commit -m "[skip ci] format" && git push)

      - name: Run deno lint
        run: deno task lint

      - name: Run deno test
        run: deno task test

      - name: Run deno build
        run: deno task build

      - name: Run commit if pull request
        if: github.event_name == 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || (git commit -m "[skip ci] update build artifacts" && git push)

      - name: Verify no diff on main branch push
        if: github.event_name == 'push'
        run: |
          git diff --exit-code
